### PR TITLE
 added some profile changes and a new picture

### PR DESCRIPTION
**Pull request by johnchase**

### CODE REVIEW

**Comment by gregcaporaso** [comment]
@johnchase, we actually need to add your office hours in the gregcaporaso/teaching-website-source repo, not here (the html here is built automatically). Can you remove that change from this PR, and I'll add to the other repo? I can show you how I update the teaching website so you can do it in the future (I have a build script that makes it really easy).

**Comment by gregcaporaso** [comment]
@johnchase, note that there is a conflict now that I've updated your office hours using my build script.

**Comment by johnchase** [comment]
@gregcaporaso I changed the file back to what it was originally.

**Comment by gregcaporaso** [comment]
@johnchase, something went wrong with this and you've got all of everyone else's commits included. Can you submit a new pull request with just the updates to your picture and profile? I think that will be easier than trying to fix this one.

**Pull request closed without merging**
